### PR TITLE
fix some bugs and add closed height

### PR DESCRIPTION
**Pull request by kahirokunn**
Nice to meet you!
I would be happy if you receive the improved code!

## DEMO
https://jsfiddle.net/kahirokunn/qjyd6935/40

### 1. Responsive height
The height of the elements in the slide may change.
If the existing code is fixed the height is not supported.

### 2. Closed Height
Also, every design when the slide is closed may not necessarily have a height of zero. In some cases you may want to peek inside the component a little.
We also addressed those needs with the closed height attribute.

### CODE REVIEW

**Comment by danieldiekmeier** [comment]
When creating a PR, please make sure to only change the things that you actually want to change.

You changed a lot of the formatting, which makes the diff hard to read. Also, I quite liked the formatting before (I wrote it!) and it didn't need changing.

Also, you removed some features I recently added (like the computed `el`), which I do not want removed.

So, thanks for the PR, but I have to decline.

**Comment by k-okina** [comment]
How about touching the demo I created once.
The contents that I modified are more stable than the current vue - slide - up - down, and it should be able to cope with many unresponsive scenes.
This should give a lot of benefits to those actually using vue-slide-up-down.

**Comment by k-okina** [comment]
Will not you give the user a better experience by raising this OSS together?
If you are concerned about differences in minor manners, please let me fix it together.

**Comment by kahirokunn** [comment]
can I fork this repository and make a new non package?

**Comment by kahirokunn** [comment]
I wanna make a more features slide up down component.

**Comment by danieldiekmeier** [comment]
Sure, go for it.

Looks like you already did: https://github.com/k-okina/vue-slide-up-down-component

**Comment by kahirokunn** [comment]
Thank you very much👏👏👏

**Pull request closed without merging**
